SELECT
	  'Loan #'								= p.LoanNumber
	, 'CB LOAN NUMBER'						= ''
	, 'BORROWER FIRST'						= upper(lca.FirstName)
	, 'BORROWER LAST'						= upper(lca.LastName)
	, 'BORROWER TAX ID'						= br.SocialSecurityNumber
	, 'BORROWER PHONE NBR'					= br.HomeAreaCode + '-' + br.HomePrefix + '-' + br.HomeLineNumber
	, 'PROPERTY CO-OWNER FIRST'				= ''
	, 'PROPERTY CO-OWNER LAST'				= ''
	, 'PROPERTY CO-OWNER TAX-ID'			= ''
	, 'PURCHASE CONTRACT DATE'				= ''
	, 'PURCHASE PRICE'						= ''
	, 'PURPOSE CODE'						= ''
	, 'LIEN TYPE'							= ''
	, 'LOAN START DATE'						= p.OriginationDate
	, 'ORIGINAL LOAN TERM IN MONTHS'		= p.Term
	, 'ORIGINAL PRINCIPAL BALANCE'			= p.LoanAmount
	, 'CURRENT PRINCIPAL BALANCE'			= p.PrincipalBalance
	, 'ACCRUED INTEREST'					= p.AccruedInterest
	, 'ORIGINAL LTV'						= ''
	, 'CURRENT BALANCE LTV'					= ''
	, 'NOTE INITIAL RATE'					= p.BorrowerRate
	, 'NOTE RATE TYPE'						= 'Fixed'
	, 'NOTE MARGIN FIXED'					= 'Yes'
	, 'NOTE MARGIN PERCENTAGE'				= ''
	, 'NOTE INTEREST INDEX'					= '' 
	, 'MAX RATE INCREASE'					= ''
	, 'MINIMUM RATE INCREASE'				= ''
	, 'NOTE MINIMUM INTEREST RATE'			= ''
	, 'NOTE MAXIMUM INTEREST RATE'			= ''
	, 'INTEREST RATE RESET INTERVAL'		= ''
	, 'NEGATIVE AMORT  ALLOWED'				= ''
	, 'MONTHS TO 1st ADJUSTMENT'			= ''
	, 'MONTHS TO NEXT ADJUSTMENT'			= ''
	, 'INITIAL REPRICING FREQUENCY'			= ''
	, 'NEXT ADJUSTMENT DATE'				= ''
	, 'ARM INITIAL INTEREST RATE'			= ''
	, 'ARM INITIAL P&I'						= ''
	, 'ESCROW BAL'							= ''
	, 'P & I'								= ''
	, 'T & I'								= ''
	, 'TOTAL SCHEDULED PMT'					= p.MonthlyPaymentAmount
	, 'REMAINING TERM (IN MONTHS)'			= p.Term - p.AgeInMonths
	, 'MATURITY DATE'						= p.MaturityDate
	, 'INTEREST PAID TO DATE'				= p.InterestPaid
	, 'FIRST PAYMENT DUE DATE'				= p.FirstScheduledPayment
	, 'NEXT DUE DATE'						= p.NextPaymentDueDate
	, 'MTG IS CURRENT (Yes or No)'			= ''
	, 'PENDING PAYMENT EFFECTIVE DATE'		= ''
	, 'PENDING P&I'							= ''
	, 'PENDING T&I'							= ''
	, 'PENDING TOTAL'						= ''
	, 'ACH PAYMENT'							= case when p.IsAutoAchOff = 0 then 'TRUE' else 'FALSE' end
	, 'GRACE DAYS'							= 0
	, 'LATE CHARGE FACTOR'					= 0.05
	, 'DTI RATIO'							= lca.DTIwoProsperLoan
	, 'CREDIT SCORE'						= lca.FICOScore
	, 'CREDIT SCORE DATE'					= lca.FICOReportDate
	, 'SSN_VERIFY_DATE'						= lca.FICOReportDate 
	, 'SSN CERTIFY DATE'					= ''
	, 'Lending Division'					= ''
	, 'Lending Officer'						= ''
	, 'Branch ID'							= ''
	, 'PRIMARY /Mailing STREET NUMBER'		= upper(br.AddressLine1)
	, 'STREET DIRECTIONAL'					= ''
	, 'PRIMARY /Mailing STREET NAME'		= ''
	, 'STREET SUFFIX'						= ''
	, 'STREET DIRECTIONAL SUFFIX'			= ''
	, 'UNIT DESIGNATION'					= ''
	, 'UNIT #'								= ''
	, 'PRIMARY / Mailing CITY'				= upper(br.City)
	, 'PRIMARY ADDRESS STATE'				= upper(br.StateCode)
	, 'PRIMARY ADDRESS ZIP'					= upper(br.ZipCode)
	, 'Collateral Code'						= ''
	, 'PROPERTY TYPE DESCRIP (per apprsl)'	= ''
	, 'PURPOSE DESCRIPTION'					= ''
	, 'OWNERSHIP TYPE'						= ''
	, 'COLLATERAL STREET NBR'				= ''
	, 'STREET DIRECTIONAL'					= ''
	, 'COLLATERAL STREET NAME'				= ''
	, 'STREET SUFFIX'						= ''
	, 'STREET DIRECTIONAL SUFFIX'			= ''
	, 'UNIT DESIGNATION'					= ''
	, 'UNIT NUMBER'							= ''
	, 'COLLATERAL CITY'						= ''
	, 'COLLATERAL COUNTY'					= ''
	, 'COLLATERAL STATE'					= ''
	, 'COLLATERAL ZIP CODE'					= ''
	, 'COLLATERAL PROPERTY VALUE'			= ''
	, 'COLLATERAL APPRAISAL DATE'			= ''
	, 'YEAR BUILT'							= ''
	, 'PROP CENSUS TRACT'					= ''
	, 'NUMBER OF UNITS'						= ''
	, 'DEVELOPMENT TYPE'					= ''
	, 'FLOOD_ZONE'							= ''
	, 'FLOOD INS REQ'						= ''
	, 'MERS'								= ''
	, 'MERS ORIG ORG ID'					= ''
	, 'MERS ORIG NOTE HOLDER NAME'			= ''
	, 'PRIMARY BORROWER NAME FIRST'			= ''
	, 'PRIMARY BORROWER NAME MIDDLE'		= ''
	, 'PRIMARY BORROWER NAME LAST'			= ''
	, 'PRIMARY TELEPHONE NUMBER'			= ''
	, 'SECOND PHONE NUMBER'					= ''
	, 'EMAIL ADDRESS'						= ''
	, 'BORROWER SHORT NAME'					= ''
	, 'DOB PRIMARY BORROWER'				= ''
	, 'BORROWER IS CB EMPLOYEE'				= ''
	, 'COBORROWER # 1 NAME FIRST'			= ''
	, 'COBORROWER # 1  NAME MIDDLE'			= ''
	, 'COBORROWER # 1  NAME LAST'			= ''
	, 'COBORROWER # 1 TELEPHONE NUMBER'		= ''
	, 'SECOND TELEPHONE NUMBER'				= ''
	, 'CO BORROWER EMAIL ADDRESS'			= ''
	, 'DOB COBORROWER # 1'					= ''
	, 'PROP MSA CODE'						= ''
	, 'STATE CODE'							= ''
	, 'COUNTY CODE'							= ''
	, 'FIPS COUNTY CODE'					= ''
	, 'ADDITIONAL COBORROWER # 2 FULL NAME' = ''
	, 'ADDITIONAL COBORROWER # 3 FULL NAME' = ''
	, 'ECLOSE (Yes or No)'					= ''
	, 'CEMA LOAN (Yes or No)'				= ''
	, 'ORIGINAL COMPANY NAME'				= ''
	, 'ORIG CO. TEL Number'					= ''
	, 'Business Type'						= ''
	, 'Relationship Name'					= ''
	, 'Relationship ID'						= ''
	, 'Stock Symbol'						= ''
	, 'Commitment Availability'				= ''
	, 'Last Renewal Date'					= ''
	, 'Last Extension Date'					= ''
	, 'Number of Renewals'					= ''
	, 'Number of Extensions'				= ''
	, 'Interest Earned Not Collected'		= ''
	, 'Borrower Internal Rating'			= ''
	, 'Borrower Rating Date'				= ''
	, 'Note Risk Rating'					= ''
	, 'Balance Rated Pass'					= ''
	, 'Balance Rated Special Mention'		= ''
	, 'Balance  Rated Sub-standard'			= ''
	, 'Balance Rated Doubtful'				= '' 
	, 'Charge-Off Amount'					= isnull(p.PrincipalBalanceAtChargeoff, 0)
	, 'Specific Reserve'					= ''
	, 'Shared National Credit'				= ''
	, 'Guarantor'							= ''
	, 'Days Past Due'						= p.DaysPastDue
	, 'Non-Accrual'							= ''
	, 'Times Past Due 30-59'				= ''
	, 'Times Past Due 60-89'				= ''
	, 'Times Past Due 90+'					= ''
	, 'Type'								= ''
	, 'FFEIC Call Code Default'				= ''
	, 'Collateral Description'				= ''
	, 'Payment Frequency'					= 'Monthly'
	, 'Variable Rate'						= 'N'
	, 'Troubled Debt Restructure'			= '' 
	, 'Amoritizing=Y / Non-Amoritizing=N'	= 'Y'
	, 'Last Payment Date'					= ''
	, 'Capitalized Interest'				= ''
	, 'Dealer Code'							= ''
	, 'Dealer Reserve Balance'				= ''
	, 'Late Charges Due & Unpaid'			= p.AccruedLatefee
	, 'Servicing Fee'						= 0.01075
	, 'Accrual Method'						= 'Actual days / 365 days'
	, 'Last Repricing Date'					= ''
	, 'Amortization Code Default'			= ''
	, 'Balloon Indicator Default'			= ''
	, 'Interest Payment Frequency'			= 1
	, 'Principal Payment Frequency'			= 1
	
	FROM
		#Positions p
	JOIN 
		#listingcreditattributes lca
		ON 
		lca.LoanNumber = p.LoanNumber
	JOIN
		#BorrowerDataFinal br
		ON
		br.LoanID = p.LoanNumber
	WHERE
		1=1 
		and p.OriginationDate < dateadd(day,1,eomonth(getdate(),-1))
		and p.OriginationDate >= dateadd(month, -1, dateadd(day,1,eomonth(getdate(),-1)))